### ISSUE TITLE
Инструкция: Как вывести звук на bluetooth колонку?

### ISSUE THREAD

**Issue by DivanX10** [Navatusein/Silero-TTS-Service#17]
Спасибо вам за эту интеграцию с нормальным синтезом речи. Хотел бы добавить мануал как добавить вывод звука, если имеется  bluetooth колонка. Все дело в том, что в документации пишется, что надо добавить в configuration.yaml и это конечно работает, но при выборе объекта, куда будем выводить звук может не оказаться bluetooth колонки. Я долго искал решение и нашел. Думаю, что, кто с этим столкнется, это будет полезным и сократит время.

```
tts:
  - platform: marytts
    host: localhost # Адрес сервера
    port: 9898
    codec: WAVE_FILE
    voice: xenia # Имя голоса который хотите использовать.
    language: ru # Не используется. Настройки языка указываются в настройках сервера.
``` 

1) Если Home Assistant как основная ОС (HAOS), то читаем эту документацию [TTS Bluetooth Speaker for Home Assistant](https://github.com/pkozul/ha-tts-bluetooth-speaker)

2) Если Home Assistant стоит на Debian, то делаем следующее

Отредактируем client.conf
```
nano /etc/pulse/client.conf
```

Добавим следующее
```
default-server = unix:/usr/share/hassio/audio/external/pulse.sock
autospawn = no
```
![image](https://user-images.githubusercontent.com/64090632/224732363-0acad78f-e0e7-46ff-99ab-e2d6e5f4254c.png)

Перезапускаем pulseaudio
```
pulseaudio -k && pulseaudio --start
```

Ставим аддон [Mopidy версии Current version: 2.1.1](https://github.com/Llntrvr/Hassio-Addons) и ставим только эту версию. Mopidy 2.2.0 не ставить - она сломанная. Подробнее про поломанную версию Mopidy 2.2.0 читать [здесь](https://github.com/Poeschl/Hassio-Addons/issues/334)

Добавляем в configuration.yaml

```
#MPD music player daemon
media_player:
  - platform: mpd
    name: "MPD Mopidy"
    host: localhost
    port: 6600
```

Перезагружаем Home Assistant полностью, чтобы перезагрузился сам Debian
![image](https://user-images.githubusercontent.com/64090632/224734211-3a55095d-7599-4651-b77f-04eecf91b307.png)

Подключаем bluetooth колонку к Debian, kb,j через GUI, либо через консоль используя команду bluetoothctl

Включим bluetooth 
```
power on
```

Запуск сканирования девайсов
```
scan on
```

Как увидели свой девайс, спариваемся с устройством
```
pair mac адрес девайса
```

Подключаемся к устройству
```
connect mac адрес девайса
```

Добавляем устройство в доверенные
```
trust  mac адрес девайса
```

Далее, как добавлен bluetooth девайс то в двух аддонов Rhasspy Assistant и Mopidy нужно указать источник вывода звука bluetooth девайса

1) В Rhasspy Assistant указываем так
![image](https://user-images.githubusercontent.com/64090632/224735611-f5cb29d4-d872-40f2-914c-4e9b586bade9.png)

2) В Mopidy указываем так
![image](https://user-images.githubusercontent.com/64090632/224736361-cc666050-d0ae-474c-b523-d5b0670ce83a.png)

После этого открываем Панель разработчика => Службы
Вид в текстовом файле
![image](https://user-images.githubusercontent.com/64090632/224736672-c11570ed-2fb5-48ba-afa8-679f670444c8.png)
```
service: tts.marytts_say
data:
  entity_id: media_player.mpd_mopidy
  message: >-
    Спустя 15 лет жизнь некогда бороздившего космические просторы Жана-Люка
    Пикара
```

Вид в GUI
![image](https://user-images.githubusercontent.com/64090632/224737298-d90d3141-689c-4fc2-9056-430d0f663ee6.png)
