### ISSUE TITLE
.HA_FIX contains true

### ISSUE THREAD

**Issue by Omirax** [Navatusein/Silero-TTS-Service#5]
Приветствую!

>Исправление обрубания окончания фразы HA_FIX:
HA_FIX: True 

services.silero-tts-service.environment.HA_FIX contains true, which is an invalid type, it should be a string, number, or a null
Работает только 
HA_FIX: 1
HA_FIX: 0
Но, как показалось, не факт, что оно работает.

**Comment by Navatusein** [comment]
> Приветствую!
> 
> > Исправление обрубания окончания фразы HA_FIX:
> > HA_FIX: True
> 
> services.silero-tts-service.environment.HA_FIX contains true, which is an invalid type, it should be a string, number, or a null Работает только HA_FIX: 1 HA_FIX: 0 Но, как показалось, не факт, что оно работает.

HA_FIX: True У меня работает и через docker run, и через portainer. Ни каких проблем нету.

А по поводу того что оно не работает. С начала оно в конец добавляло задержку в 3 секунды. Но это много и я снизил до 1 секунды. Послушал и вроде как хватает. 

Думаю, я добавлю чтобы пре запуске выводило в логи настройки, для удобства отладки.

**Comment by Omirax** [comment]
```
    environment:
      NUMBER_OF_THREADS: 4
      LANGUAGE: ru
      SAMPLE_RATE: 8000
      HA_FIX: True
```
compose выдает ошибку, что я написал выше

**Comment by Navatusein** [comment]
> ```
>     environment:
>       NUMBER_OF_THREADS: 4
>       LANGUAGE: ru
>       SAMPLE_RATE: 8000
>       HA_FIX: True
> ```
> 
> compose выдает ошибку, что я написал выше

Попробуйте поменять `True` на `yes`.

**Comment by Omirax** [comment]
>Попробуйте поменять True на yes.

Не помогает.

**Comment by Navatusein** [comment]
К сожалению я пока не могу у себя проверять. Уже 2 сутки нету света а на ноуте не могу собрать контейнер ибо зависимости не хотят качаться через мобильный интернет.

**Comment by Navatusein** [comment]
Проверил у себя с Docker Compose всё работает.
Вот мой файлик:

```yaml
version: '3'

services:
  silero-tts-service:
    image: "navatusein/silero-tts-service"
    container_name: "silero-tts-service"
    ports:
      - "9898:9898"
    restart: unless-stopped
    environment:
      NUMBER_OF_THREADS: 4
      LANGUAGE: ru
      SAMPLE_RATE: 48000
      HA_FIX: True
```

**Comment by Omirax** [comment]
У меня заработало только с таким синтаксисом

```
version: '3.4'

services:
  silero-tts-service:
    image: "navatusein/silero-tts-service"
    container_name: "silero-tts-service"
    ports:
      - "9898:9898"
    restart: unless-stopped
    environment:
     - NUMBER_OF_THREADS=4
     - LANGUAGE=ru
     - HA_FIX=true
     - SAMPLE_RATE=8000
```
